- hosts: web
  remote_user: evan
  become: true
  tasks:
    - name: test connection
      ping:

    - name: Net-tools is present
      apt: name=net-tools state=present

    - name: Unattended-upgrades is present
      apt: name=unattended-upgrades state=present

    - name: Fail2Ban is present
      apt: name=fail2ban state=present

    - name: Nginx is installed
      apt: name=nginx state=present
